require 'rake'
require 'rspec/core/rake_task'
require 'yaml'

task :spec    => 'spec:all'
task :default => :spec

namespace :spec do
  targets = []
  inventory = YAML.load(`ansible-inventory --list -i ../.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory`)
  inventory['_meta']['hostvars'].keys.each do |host|
    target = "_#{target}" if host == "default"
    targets << target
  end

  task :all     => targets
  task :default => :all

  targets.each do |target|
    original_target = target == "_default" ? target[1..-1] : target
    desc "Run serverspec tests to #{original_target}"
    RSpec::Core::RakeTask.new(target.to_sym) do |t|
      ENV['TARGET_HOST'] = original_target
      t.pattern = "spec/#{original_target}/*_spec.rb"
    end
  end
end
