---
# code: language=ansible
- name: Generate operational and maintenance report
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - name: Update package cache and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
  roles:
    - role: report
      tags: role_report
  tasks:
    - name: Create symbolic links to the document root in the home directory
      ansible.builtin.import_role:
        name: utils
        tasks_from: filesystem/symlink
      tags: filesystem_symlink
  post_tasks:
    - name: Cleanup packages
      ansible.builtin.apt:
        autoremove: true
